version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'dominik'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'dominik-db'
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  next-app:
    build: .
    environment:
      DATABASE_URL: 'postgresql://dominik:password@db:5432/dominik-db?schema=sample'
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres-data:
